BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `students` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT NOT NULL,
	`course`	TEXT NOT NULL,
	`age`	INTEGER NOT NULL
);
INSERT INTO `students` VALUES (1,'Bartosz','GiG',22);
INSERT INTO `students` VALUES (2,'Arek','WiG',23);
INSERT INTO `students` VALUES (3,'Magda','WiG',24);
COMMIT;
